### PR TITLE
CSIT PIP3 requirements

### PR DESCRIPTION
**Pull request by pmikus**
Please merge the https://github.com/snergfdio/csit-sut/pull/4 first so we will know it works.

### CODE REVIEW

**Comment by pmikus** [comment]
Where can i see the ci/dockercloud logs?

**Comment by snergfdio** [comment]
do you not see the link to see the dockercloud logs?  lets to a screen share next week so i can see what you see...its failing on robotframework line

**Comment by pmikus** [comment]
When clicking on Details link of ci/dockercloud i do see only this:

image

**Comment by snergfdio** [comment]
Could not find a version that satisfies the requirement numpy==1.17.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5)
No matching distribution found for numpy==1.17.3

**Pull request merged**
